### ISSUE TITLE
Inadequate edit group summary (only part after comma chosen)

### ISSUE THREAD

**Issue by lucaswerkmeister** [Wikidata/editgroups#4] opened 2018-06-16 18:14 UTC
In [this edit group](https://tools.wmflabs.org/editgroups/b/OR/6594554/), done with OpenRefine, I used the following edit summary:

> import some Theodor Heuss awards and medals, see award item talk page for more information

However, on the edit group page the summary is given as

> see award item talk page for more information

which is the less useful half of the summary :)

---

I assume that the tool tries to split up the full edit summary

> Created claim: [Property:P166]: [Q55064109], import some Theodor Heuss awards and medals, see award item talk page for more information ([details])

into auto-summary (<q>Created claim: [Property:P166]: [Q55064109]</q> – everything before the <em>first</em> comma), custom summary (<q>import some Theodor Heuss awards and medals, see award item talk page for more information</q>) and EditGroups link (<q>([details])</q>), and the regex should be tweaked to make the auto-summary part less greedy, to split on the first comma in the full summary instead of the last one?

Unfortunately, I can’t seem to find the configuration for the individual tools in this repository, except in [this migration script](https://github.com/Wikidata/editgroups/blob/master/store/migrations/0002_populate_tools.py), which I assume is out-of-date (it doesn’t mention the “custom bot” tool, for one).

[Property:P166]: https://www.wikidata.org/wiki/Property:P166
[Q55064109]: https://www.wikidata.org/wiki/Q55064109
[details]: https://tools.wmflabs.org/editgroups/b/OR/6594554

**Comment by wetneb** [comment] 2018-06-16 18:50
The regex currently is the one from the migration… and yeah, it does not work well! To be honest I was aware of the issue when writing it but I am not sure how to fix it… The issue is that the user-provided summaries do not always start after the first comma. It depends a lot on the action type.

For instance say you add a description, it will look like this:
`/* wbsetdescription-add:1|en */ a long description, with some commas in it, importing my awesome database`
No idea how to deal with that!

One other idea would be not to collect the first few summaries and keep the longest common suffix of them, maybe… but if you are always adding the same description then this is also going to end up in the summary… I really don't know! But happy to change the regex for sure.

**Comment by wetneb** [comment] 2019-02-23 08:33
I went for a hopefully bullet-proof solution which consists in replacing commas in summaries by a very similar Unicode character. It's ugly but I find it funny.

**Comment by wetneb** [comment] 2019-02-23 11:01
Closing after successful testing: https://tools.wmflabs.org/editgroups/b/OR/6488cf935/

**Closed by wetneb** 2019-02-23 11:01 UTC
